In [ ]:
# %pip install seaborn

In [1]:
# Tips 데이터셋
## seaborn 내장 데이터넷
import seaborn as sns
import pandas as pd

In [2]:
# 1. 사용 가능한 데이터셋 확인
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
# 2. 데이터 로드 방법
# sns.load_dataset('데이터셋이름')
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
# 3. 데이터 구조
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [6]:
# 4. 데이터 분포
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
# 5. 범주형 데이터의 탐색
# 성별
# df['컬럼명'].unique(): 유일한 값들
df['sex'].unique()

['Female', 'Male']
Categories (2, str): ['Male', 'Female']

In [7]:
# df.['컬럼명'].value_counts(): 각 값의 개수
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [9]:
# 전체 범주형 데이터 요약
# 모든 범주형 변수의 고유값 개수
categorical_columns = df.select_dtypes(include=['category']).columns
categorical_columns

Index(['sex', 'smoker', 'day', 'time'], dtype='str')

In [10]:
# df['컬럼명'].nunique(): 고유값 개수
# df['컬럼명'].unique(): 고유값 리스트
for col in categorical_columns:
    print(f'{col}: {df[col].nunique()}개의 고유값')
    print(f'   값: {list(df[col].unique())}')
    print()

sex: 2개의 고유값
   값: ['Female', 'Male']

smoker: 2개의 고유값
   값: ['No', 'Yes']

day: 4개의 고유값
   값: ['Sun', 'Sat', 'Thur', 'Fri']

time: 2개의 고유값
   값: ['Dinner', 'Lunch']