In [28]:
# 특성 공학
'''
문5-6> 주어진 데이터를 사용해서 판매량을 예측하는 선형 회귀 모델을 생성하고자 한다. 
아래 조건에 알맞은 신규 특성(Feature)을 생성하시오.
- 'year'(연도), 'month'(월), 'day'(일), 'weekday'(요일, 월요일:0, 일요일:6), 'is_weekend'(주말 여부, 주말:1, 평일:0), 'quarter'(분기, 1~4) 속성 생성
'''

import sklearn

# 모델 다이어그램 출력을 텍스트 형식으로 변경
sklearn.set_config(display="text")

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [29]:

# 특성 생성: 날짜 데이터로부터 다양한 특성 추출하기
# 날짜 데이터 생성
np.random.seed(42)
dates = pd.date_range('2023-01-01', periods=100, freq='D')
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
               '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
               '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
               '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
               '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01',
               '2023-03-02', '2023-03-03', '2023-03-04', '2023-03-05',
               '2023-03-06', '2023-03-07', '2023-03-08', '2023-03-09',
               '2023-03-10', '2023-03-11', '2023-03-12', '2023-03-13',
               '2023-03-14', '2023-03-15', '2023-03-16', '2023-03-17',
               '2023-03-18', '2023-03-19', '2023-03-20', '2023-03-21',
               '2023-03-22', '2023-03-23', '2023-03-24', '2023-03-25',
               '2023-03-26', '2023-03-27', '2023-03-28', '2023-03-29',
               '2023-03-30', '2023-03-31', '2023-04-01', '2023-04-02',
               '2023-04-03', '2023-04-04', '2023-04-05', '2023-04-06',
               '2023-04-07', '2023-04-08', '2023-04-09', '2023-04-10'],
              dtype='datetime64[us]', freq='D')

In [30]:
# 가상의 판매량 데이터 생성
sales = np.random.randint(50, 200, size=100)
sales

array([152, 142,  64, 156, 121,  70, 152, 171, 124, 137, 166, 149, 153,
       180, 199, 102,  51, 137,  87, 179,  70, 107,  71, 138,  98, 108,
        64, 100, 157, 104, 113, 180, 100, 184,  70, 122,  67, 181, 138,
       109,  63,  58, 139, 102, 179, 133, 141, 160,  57,  84, 130,  99,
       153, 181,  51, 183, 103, 155,  53, 103, 195,  93,  63, 144,  97,
        64,  89, 131, 160, 102,  73, 173,  90,  64,  94, 114, 138, 120,
        58, 137, 178, 185, 112, 188, 130, 185,  82, 172,  54,  90,  77,
       184, 121,  61,  82,  97, 111,  86, 148, 153], dtype=int32)

In [31]:
# 데이터 프레임 생성
df = pd.DataFrame({'date': dates, 'sales': sales})
df

         date  sales
0  2023-01-01    152
1  2023-01-02    142
2  2023-01-03     64
3  2023-01-04    156
4  2023-01-05    121
..        ...    ...
95 2023-04-06     97
96 2023-04-07    111
97 2023-04-08     86
98 2023-04-09    148
99 2023-04-10    153

[100 rows x 2 columns]

In [32]:
# 날짜 데이터에서 다양한 특성 추출
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.weekday # 월요일=0, 일요일=6
df['is_weekend'] = (df['date'].dt.weekday >= 5)*1 # 주말 여부 (주말은 1, 평일은 0)
df['quarter'] = df['date'].dt.quarter # 분기 (1, 2, 3, 4분기)

df.head()

        date  sales  year  month  day  weekday  is_weekend  quarter
0 2023-01-01    152  2023      1    1        6           1        1
1 2023-01-02    142  2023      1    2        0           0        1
2 2023-01-03     64  2023      1    3        1           0        1
3 2023-01-04    156  2023      1    4        2           0        1
4 2023-01-05    121  2023      1    5        3           0        1

In [33]:
# 특성 변환: 표준화
'''
문5-7> 문5-6의 수행 결과(df)에 대해 학습용 데이터와 테스트용 데이터를 분할하고, 학습용 데이터에 대해 표준화를 사용해서 변환하시오.
- 독립변수는 문5-6에서 생성한 신규 속성 6개, 종속변수는 'sales'
- 데이터 분할: 학습용:테스트용 = 8:2
- random_state = 42로 설정
'''
# 특성 및 목표 변수 설정
X = df[['year', 'month', 'day', 'weekday', 'is_weekend', 'quarter']]
y = df['sales']

# 데이터 분할
# 학습 데이터와 테스트 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
# 특성 스케일 조정 (표준화)
scaler = StandardScaler()

In [35]:
# 학습 데이터에 fit을 하고 변환 (스케일 조정)
X_train_scaled = scaler.fit_transform(X_train)

# 테스트 데이터에 transform만 수행 (학습 데이터 기준으로 변환)
X_test_scaled = scaler.transform(X_test)

In [36]:
# 선형 회귀 모델 학습 및 평가
'''
문5-8> 문5-7에서 변환한 학습 데이터를 사용하여 모델을 선형 회귀 모델을 학습하고, 각 특성에 해당하는 회귀계수를 출력하시오. 테스트 데이터를 사용하여 학습 결과의 성능을 확인하기 위한 적절한 평가 지표를 설정하여 소수점 4자리까지 출력하시오.
'''
# 모델 정의 및 훈련
model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [37]:
# 모델 회귀계수 출력
print('회귀계수:')
coefficients = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])
print(coefficients)

print(f'절편: {model.intercept_}')

회귀계수:
            Coefficient
year           0.000000
month         -2.833395
day           -0.699444
weekday        2.169846
is_weekend     1.470717
quarter        1.201252
절편: 116.6

In [38]:
# 예측 및 평가
y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)

print(f'평가 지표(MSE): {round(mse, 4)}')

평가 지표(MSE): 2026.2703